### PR TITLE
MemoryFileSystem addStream onError

### LINKED ISSUE #219: MemoryFileSystem addStream misbehaves on error
The following test code throws a `Bad state: Future already completed`:

```dart
final file = MemoryFileSystem.test().file('foo').openWrite();
try {
  await file.addStream(Stream.error('bar'));
  await file.flush();
} finally {
  await file.close();
}
```

It looks like `memory_file.dart` is doing suspicious things in its [`addStream` `onError`](https://github.com/google/file.dart/blob/b9051806a1fde54066d080a2a3f00333c7bae415/packages/file/lib/src/backends/memory/memory_file.dart#L428-L429):

```dart
  @override
  Future<void> addStream(Stream<List<int>> stream) {
    _checkNotStreaming();
    _streamCompleter = Completer<void>();
    void finish() {
      _streamCompleter!.complete();
      _streamCompleter = null;
    }

    stream.listen(
      (List<int> data) => _addData(data),
      cancelOnError: true,
      onError: (Object error, StackTrace stackTrace) {
        _completer.completeError(error, stackTrace);
        finish();
      },
      onDone: finish,
    );
    return _streamCompleter!.future;
  }
```

By my reading, I suspect `onError` should be routing the error to `_streamCompleter` rather than `_completer`, and setting `_streamCompleter` to null rather than calling `finish()`?

### PR DESCRIPTION
**Pull request by AsturaPhoenix**
Route stream errors to the stream completer rather than the file completer.

Fixes #219

### CODE REVIEW

File: packages/file/lib/src/backends/memory/memory_file.dart [hunk 1]
```diff
@@ -416,19 +416,18 @@ class _FileSink implements io.IOSink {
...
       (List<int> data) => _addData(data),
       cancelOnError: true,
       onError: (Object error, StackTrace stackTrace) {
-        _completer.completeError(error, stackTrace);
-        finish();
+        _streamCompleter!.completeError(error, stackTrace);
+        _streamCompleter = null;
+      },
+      onDone: () {
+        _streamCompleter!.complete();
```
Comment (jakemac53) [inline packages/file/lib/src/backends/memory/memory_file.dart:428]: you might want to check for `isCompleted` here and only call `complete` in that case.

Comment (AsturaPhoenix) [reply packages/file/lib/src/backends/memory/memory_file.dart:428]: It looks like that's unnecessary since `cancelOnError` is true. I can add a test that exercises this if you think it's a good idea.

Here's the test that I used to check this:

```dart
  test(
      'addStream completes on error and does not misbehave if the stream '
      'produces multiple errors and then closes', () async {
    final file = MemoryFileSystem.test().file('foo').openWrite();
    final controller = StreamController<List<int>>()
      ..addError('bar')
      ..addError('baz')
      ..close();
    await expectLater(file.addStream(controller.stream), throwsA('bar'));
    await file.close();
  });
```

Comment (AsturaPhoenix) [reply packages/file/lib/src/backends/memory/memory_file.dart:428]: We could also await the `StreamController.close` for more confidence:

```dart
  test(
      'addStream completes on error and does not misbehave if the stream '
      'produces multiple errors and then closes', () async {
    final file = MemoryFileSystem.test().file('foo').openWrite();
    final controller = StreamController<List<int>>()
      ..addError('bar')
      ..addError('baz');
    final close = controller.close();
    await expectLater(file.addStream(controller.stream), throwsA('bar'));
    await file.close();
    await close;
  });
```

Comment (AsturaPhoenix) [reply packages/file/lib/src/backends/memory/memory_file.dart:428]: Oh, derp, also, since we set `_streamCompleter` to null anywhere we complete it, we'd be unable to complete it multiple times regardless.

File: packages/file/lib/src/backends/memory/memory_file.dart [hunk 2]
```diff
@@ -416,19 +416,18 @@ class _FileSink implements io.IOSink {
...
-      _streamCompleter = null;
-    }
 
     stream.listen(
       (List<int> data) => _addData(data),
       cancelOnError: true,
       onError: (Object error, StackTrace stackTrace) {
-        _completer.completeError(error, stackTrace);
-        finish();
+        _streamCompleter!.completeError(error, stackTrace);
```
Comment (jakemac53) [inline packages/file/lib/src/backends/memory/memory_file.dart:424]: Actually, just to be safe these should probably be `?.`s? I think it might be possible to get both an error on a stream as well as a done event?

File: packages/file/lib/src/backends/memory/memory_file.dart (hunk 1 above)
Comment (jakemac53) [reply packages/file/lib/src/backends/memory/memory_file.dart:428]: SGTM, although see my other comment that I do think we should change to using `?.`.

File: packages/file/lib/src/backends/memory/memory_file.dart (hunk 2 above)
Comment (AsturaPhoenix) [reply packages/file/lib/src/backends/memory/memory_file.dart:424]: Not with `cancelOnError`:

https://api.flutter.dev/flutter/dart-async/Stream/listen.html#:~:text=If%20cancelOnError%20is,functions%20are%20called.

More specifically, it's only possible if the stream implementation doesn't respect the subscription cancel, which is the kind of error that should probably throw exceptions left and right anyway.

Comment (AsturaPhoenix) [reply packages/file/lib/src/backends/memory/memory_file.dart:424]: Although, I have seen (and seconded) some contention on the wording of this contract, while not in `cancelOnError`, on the presumably analogous but possibly asynchronous `StreamSubscription.cancel`:

https://github.com/flutter/flutter/issues/91814

Do you happen to have a case on hand that sends a done event after the `cancel` has started? I can look around to see if I have one somewhere, but it may not exist.

Comment (jakemac53) [reply packages/file/lib/src/backends/memory/memory_file.dart:424]: I don't have a specific situation or sequence of events in mind :). Good point about `cancelOnError`, although I don't love relying on that contract (also somebody could easily remove that later, and not know that these now need to be a `?.`).

It just seems like good defensive programming to me to use `?.` here, and there is little downside (other than swallowing some errors, which isn't great, but the alternative is crashing).

Comment (AsturaPhoenix) [reply packages/file/lib/src/backends/memory/memory_file.dart:424]: I made the mistake of looking at https://github.com/dart-lang/sdk/blob/main/sdk/lib/async/stream_impl.dart and now I don't know how any of it works at all.

I typically prefer crashes over swallowed errors, but I'm also quick to change my tune when it hits the UI. On the other hand, this PR would not introduce any crashes that wouldn't already have been happening, since the code was previously calling `finish()` anyway, which also accesses `_streamCompleter` and sets it to null. From that perspective, adding the defensive `?.` would constitute and additional change in behavior I'd prefer to avoid in this PR.

Comment (AsturaPhoenix) [reply packages/file/lib/src/backends/memory/memory_file.dart:424]: I'm at least going to go ahead and add the test case so that if someone does change the SDK stream impl, we have a failing unit test to let people know that something needs to be migrated.

Comment (jakemac53) [reply packages/file/lib/src/backends/memory/memory_file.dart:424]: Ok, that sgtm and its true that your PR isn't really changing this.

**Review by jakemac53 — APPROVED** [review]
